services:
  mirollama:
    image: ghcr.io/666ghj/mirofish:latest
    # Accelerate the image (if the pull is slow, you can replace the address above)
    # image: ghcr.nju.edu.cn/666ghj/mirofish:latest
    container_name: mirollama
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
